include:
  - config.d/helpers
  - config.d/cores
  - config.d/devs
  - config.d/desktops
  - config.d/optionals

vars:
  # Default Variables, can be overridden in env(must lowercase, the same)
  email: "example@email.com"
  username: "user"
  # Optional Select
  profile: "server"
  if_ddns: false
  
tasks:
  - id: welcome-msg
    group: end
    run: "echo '🎉 Environment Setup for Kie-Chi Complete! Please relogin.'"  
