#!/bin/bash
set -e

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTB_BIN="$BASE_DIR/bin/dotb"
CONFIG_FILE="$BASE_DIR/configs/config.yml"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${GREEN}-> Setting up environment from $BASE_DIR${NC}"
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}Configuration file (my.env) not found.${NC}"
    echo -e "${YELLOW}Starting interactive setup wizard...${NC}\n"

    # --- 1. Username ---
    DEFAULT_USER=$(whoami)
    echo -e "${CYAN}[?] Username${NC} (Recommended: your GitHub username)"
    read -p "    Enter username [default: $DEFAULT_USER]: " INPUT_USER
    USERNAME=${INPUT_USER:-$DEFAULT_USER}
    echo ""

    # --- 2. Email ---
    echo -e "${CYAN}[?] Email${NC} (Recommended: your GitHub email for git config)"
    read -p "    Enter email: " EMAIL
    echo ""

    # --- 3. Profile ---
    echo -e "${CYAN}[?] Profile${NC} (Select the environment type)"
    echo "    1) desktop (GNOME, GUI Apps, Fcitx5, etc.)"
    echo "    2) server  (Headless, Terminal only)"
    read -p "    Select [default: 1]: " PROF_OPT
    if [ "$PROF_OPT" == "2" ]; then
        PROFILE="server"
    else
        PROFILE="desktop"
    fi
    echo ""

    # --- 4. DDNS ---
    echo -e "${CYAN}[?] DDNS${NC} (Enable Dynamic DNS update service?)"
    read -p "    Enable DDNS? (y/N) [default: N]: " DDNS_OPT
    if [[ "$DDNS_OPT" =~ ^[Yy]$ ]]; then
        IF_DDNS="true"
        echo -e "    ${YELLOW}Note: Please manually edit my.env later to fill in DDNS secrets.${NC}"
    else
        IF_DDNS="false"
    fi
    echo ""

    # --- gen my.env ---
    echo "# Auto-generated by setup.sh on $(date)" > "$ENV_FILE"
    echo "username=$USERNAME" >> "$ENV_FILE"
    echo "email=$EMAIL" >> "$ENV_FILE"
    echo "profile=$PROFILE" >> "$ENV_FILE"
    echo "if_ddns=$IF_DDNS" >> "$ENV_FILE"

    echo -e "${GREEN}-> Configuration saved to $ENV_FILE${NC}"
    echo "----------------------------------------------------"
else
    echo -e "${GREEN}-> Loading existing configuration from $ENV_FILE${NC}"
fi

if [ -f "$DOTB_BIN" ]; then
    chmod +x "$DOTB_BIN"
else
    echo -e "${YELLOW}Warning: Binary not found at $DOTB_BIN${NC}"
    echo "Attempting to build from source (requires Go)..."
    if command -v go >/dev/null; then
        (cd "$BASE_DIR" && go build -o bin/dotb cmd/dotbuilder/main.go)
        echo -e "${GREEN}-> Build successful.${NC}"
    else
        echo "Error: Go not installed and binary missing."
        exit 1
    fi
fi

if [ ! -f "/usr/local/bin/dotb" ]; then
    if command -v sudo >/dev/null && [ "$EUID" -ne 0 ]; then
        echo "Creating symlink for dotb..."
        sudo ln -sf "$DOTB_BIN" /usr/local/bin/dotb || echo -e "${YELLOW}Warning: Failed to create symlink, skipping.${NC}"
    fi
fi
echo -e "${GREEN}-> Executing DotBuilder...${NC}"
"$DOTB_BIN" -c "$CONFIG_FILE" "$@"